name: Publish to NuGet

on:
  pull_request:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
        source-url: https://nuget.pkg.github.com/SamirBanjanovic/index.json
    - name: Build
      run: dotnet build --configuration Release
    - name: Publish
      run: dotnet nuget push Wayless/bin/Release/*.nupkg -k ${{secrets.nuget}} -s https://api.nuget.org/v3/index.json
      
