name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
        source-url: https://nuget.pkg.github.com/SamirBanjanovic/index.json
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Publish the package to nuget
      run: dotnet nuget push /home/runner/work/Wayless/Wayless/src/Wayless/bin/Release/*.nupkg -k ${{secrets.nuget}} -s https://api.nuget.org/v3/index.json
      
